language: java
arch:
  - arm64
env:
  - CC=gcc
before_install:
  - sudo apt-get -y install make

# Travis CI does not export JAVA_HOME for arm64: https://travis-ci.community/t/java-home-is-not-exported-for-arm64-architecture/6993/3
# We use an ugly hack to try and get this working.
install: skip
script:
  - 'export JAVA_HOME="$(realpath -Pm "$(which javac)/../../")"'
  - './gradlew check'

jobs:
  exclude:
    # This build fails due to a fault on Travis's end. Apparently there's no ARM64 build of OpenJDK 8, which is... weird.
    - jdk: openjdk8
      arch: arm64