language: java
arch:
  - amd64
  - arm64
jdk:
  - openjdk8
  - openjdk11
env:
  - CC=gcc
  - CC=clang
before_install:
  - sudo apt-get -y install make

# Travis CI does not export JAVA_HOME for arm64: https://travis-ci.community/t/java-home-is-not-exported-for-arm64-architecture/6993/3
script:
  - 'export JAVA_HOME="$(realpath -Pm "$(which javac)/../../")"'
  - './gradlew check'

jobs:
  exclude:
    # This build fails due to a fault on Travis's end. Apparently there's no ARM64 build of OpenJDK 8, which is... weird.
    - jdk: openjdk8
      arch: arm64