name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
        env:
          CC: gcc
          ci: true
      - uses: actions/upload-artifact@v3
        with:
          name: Linux-amd64
          path: |
              ./tmp/compiled/linux/amd64/libdeflate_jni.so
      - uses: actions/upload-artifact@v3
        with:
          name: Interface jar
          path: |
            ./libdeflate-java-core/build/libs/libdeflate-java-core-*.jar
  linux-aarch64:
    runs-on: aarch64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: compileNatives
        env:
          CC: gcc
      - uses: actions/upload-artifact@v3
        with:
          name: Linux-aarch64
          path: |
            ./tmp/compiled/linux/aarch64/libdeflate_jni.so
  windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: compileNatives
        env:
          MSVC: true
      - uses: actions/upload-artifact@v3
        with:
          name: Windows-amd64
          path: |
            ./tmp/compiled/windows/amd64/libdeflate_jni.dll
  build-full-jar:
    needs: [linux-amd64, linux-aarch64, windows-amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux-amd64
        uses: actions/download-artifact@v3
        with:
          name: Linux-amd64
          path: ./linux/amd64
      - name: Download Linux-aarch64
        uses: actions/download-artifact@v3
        with:
          name: Linux-aarch64
          path: ./linux/aarch64
      - name: Download Windows-amd64
        uses: actions/download-artifact@v3
        with:
          name: Windows-amd64
          path: ./windows/amd64
      - name: Download Interface jar
        uses: actions/download-artifact@v3
        with:
          name: Interface jar
          path: ./
      - name: Build full jar
        run: |
          jar uf libdeflate-java-core-0.0.2-PNX.jar ./linux ./windows
          mv libdeflate-java-core-0.0.2-PNX.jar libdeflate-java-0.0.2-PNX.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Full jar
          path: |
            ./libdeflate-java-0.0.2-PNX.jar
