name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
        env:
          CC: gcc
      - uses: actions/upload-artifact@v3
        with:
          name: Linux-amd64
          path: |
              ./tmp/compiled/linux/amd64/libdeflate_jni.so
  ubuntu-aarch64:
    runs-on: aarch64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: compileNatives
        env:
          CC: gcc
      - uses: actions/upload-artifact@v3
        with:
          name: Linux-aarch64
          path: |
            ./tmp/compiled/linux/*/libdeflate_jni.so
  windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
        env:
          MSVC: true
      - uses: actions/upload-artifact@v3
        with:
          name: Windows-msvc-amd64
          path: |
            ./tmp/compiled/windows/amd64/libdeflate_jni.dll
